<?php
/**
 * TL_ROOT/system/modules/glossary/languages/fr/modules.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Glossaire";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Lister des termes et leurs définitions.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Glossaire";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Menu de glossaire";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Ajoute un menu de glossaire dans le site.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Liste de glossaire";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "Ajoute une liste de glossaire dans le site.";
 
?>
