<?php
/**
 * TL_ROOT/system/modules/glossary/languages/fr/tl_glossary.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Saisir le titre.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Date de révision";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Date et heure de la dernière révision";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titre";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "La suppression d'un glossaire entraînera la suppression de tous ses termes ! Voulez-vous vraiment supprimer le glossaire ID %s ?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nouveau glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Créer un nouveau glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Détails du glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Afficher les détails du glossaire ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Éditer le glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Éditer le glossaire ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Copier le glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Copier le glossaire ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Supprimer le glossaire";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Supprimer le glossaire ID %s";
 
?>
