<?php
/**
 * TL_ROOT/system/modules/glossary/languages/fr/tl_glossary_term.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Saisir un terme.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Auteur";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Choisir un auteur.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Définition";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Saisir une définition.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Ajouter une image à la définition.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Ajouter des fichiers";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Ajouter un ou plusieurs fichiers à la définition.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Fichiers";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Choisir les fichiers que vous souhaitez joindre à la définition.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Terme et auteur";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Définition";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Paramètres de l'image";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Fichiers joints";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nouveau terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Créer un nouveau terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Détails du terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Détails du terme ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Éditer le terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Éditer le terme ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Déplacer le terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Déplacer le terme ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Copier le terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Copier le terme ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Supprimer le terme";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Supprimer le terme ID %s";
 
?>
