<?php
/**
 * TL_ROOT/system/modules/glossary/languages/fr/tl_module.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Glossaires";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Sélectionner un ou plusieurs glossaires.";
 
?>
