<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ja/modules.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "用語集";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "用語とその記述をリストします。";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "用語集";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "用語集メニュー";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "用語集メニューをウェブサイトに加えます。";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "用語リスト";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "用語リストをウェブサイトに加えます。";
 
?>
