<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ja/tl_glossary_term.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "用語";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "用語を入力してください。";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "作成者";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "用語の記述の作成者を変更できます。";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "用語の記述";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "用語の記述を入力してください。";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "画像を追加";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "用語の記述に画像を加えます。";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "添付ファイルを追加";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "用語の記述にダウンロード可能なファイルを1つ以上加えます。";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "添付ファイル";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "添付したいファイルを選択してください。";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "用語と作成者";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "用語の記述";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "画像の設定";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "添付ファイル";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "新しい用語";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "新しく用語を作成";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "用語の詳細";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "ID %sの用語の詳細を表示";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "用語を編集";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "ID %sの用語を編集";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "用語を移動";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "ID %sの用語を移動";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "用語を複製";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "ID %sの用語を複製";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "用語を削除";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "ID %sの用語を削除";
 
?>
