<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ja/tl_glossary.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "題名";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "用語集の題名を入力してください。";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "改訂日";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "最新のリビジョンの日付と時刻";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "題名";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "用語集を削除すると、そこに含まれる用語もすべて削除します。ID %sの用語集を本当に削除しますか?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "新しい用語集";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "新しく用語集を作成";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "用語集の詳細";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "ID %sの用語集の詳細を表示";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "用語集を編集";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "ID %sの用語集を編集";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "用語集を複製";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "ID %sの用語集を複製";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "用語集を削除";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "ID %sの用語集を削除";
 
?>
