<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ja/tl_module.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "用語";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "用語集を1つ以上選択してください。";
 
?>
