<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sv/modules.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Swedish translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Ordlista";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Listar uppslagsord och deras förklaringar";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Ordlista";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Ordlistemeny";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Lägger till en ordlistemeny på hemsidan.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Ordlistelista";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "Lägger till en lista över ordlistor på hemsidan.";
 
?>
