<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sv/tl_glossary_term.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Swedish translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Ange uppslagsord.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Författare";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Här kan du ange förklaringens författare.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Förklaring";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Ange en förklaring till uppslagsordet.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Lägg till bild";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Lägg till en bild till förklaringen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Bifoga fil";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Lägg till en eller fler nedladdningsbara filer till förklaringen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Källfiler";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Välj de filer som du vill bifoga till förklaringen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Uppslagsord och författare";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Förklaring";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Bildinställningar";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Bilagor";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nytt uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Skapa ett nytt uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detaljer för uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Visa detaljer för uppslagsord med ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Redigera uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Redigera uppslagsord med ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Flytta uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Flytta uppslagsord med ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopiera uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopiera uppslagsord med ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Ta bort uppslagsord";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Ta bort uppslagsord med ID %s";
 
?>
