<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sv/tl_glossary.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Swedish translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Ange ordlistans titel.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Ändringsdatum";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Datum och tid för senaste ändring.";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "När en ordlista raderas så raderas även alla ingående uppslagsord och förklaringar! Vill du verkligen radera ordlistan med ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Ny ordlista";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Skapa en ny ordlista.";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Ordlistedetaljer";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Visa detaljer för ordlista med ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Redigera ordlista";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Redigera ordlista med ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopiera ordlista";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopiera ordlista med ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Ta bort ordlista";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Ta bort ordlista med ID %s";
 
?>
