<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sv/tl_module.php 
 * 
 * Contao extension: glossary 1.2.0 stable 
 * Swedish translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Ordlistor";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Välj en eller flera ordlistor.";
 
?>
