<?php
/**
 * TL_ROOT/system/modules/glossary/languages/hr/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Kroatisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Darko Selesi (w3scout), http://w3scouts.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Pojmovnik";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Izlistaj pojmove i njihove definicije.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Pojmovnik";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Izbornik pojmovnika";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Na web stranice dodaje izbornik pojmovnika.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Lista pojmovnika";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "Na web stranice dodaje listu pojmovnika.";
 
?>
