<?php
/**
 * TL_ROOT/system/modules/glossary/languages/hr/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Kroatisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Darko Selesi (w3scout), http://w3scouts.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Upišite pojam.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Ovdje možete izmijeniti autora definicije pojma.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definicija";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Upišite definiciju.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Dodaj sliku";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Definiciji dodajte sliku.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Dodaj priloge";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Ovdje možete definiciji dodati jednu ili više datoteka za download.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Prilozi";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Odaberite datoteke koje želite dodati definiciji.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Pojam i autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definicija";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Slika članka";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Prilozi";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Novi pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Kreirajte novi pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detalji pojma";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Prikazati detalje pojma s ID %s.";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Uredi pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Uredite pojam s ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Premjesti pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Premjestite pojam s ID &s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopiraj pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopirajte pojam s ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Izbriši pojam";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Izbrišite pojam s ID %s";
 
?>
