<?php
/**
 * TL_ROOT/system/modules/glossary/languages/hr/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Kroatisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Darko Selesi (w3scout), http://w3scouts.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Naslov";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Upišite naslov pojmovnika.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Datum revizije";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Datum i vrijeme posljednje revizije.";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Naslov";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Brisanjem pojmovnika izbrisat će te i sve njegove pojmove! Zaista želite izbrisati pojmovnik s ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Novi pojmovnik";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Kreirajte novi pojmovnik.";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Detalji pojmovnika";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Prikazati detalje pojmovnika s ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Uredi pojmovnik";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Uredite pojmovnik s ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopiraj pojmovnik";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopirajte pojmovnik s ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Izbriši pojmovnik";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Izbrišite pojmovnik s ID %s";
 
?>
