<?php
/**
 * TL_ROOT/system/modules/glossary/languages/lv/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Lettisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Ivo Simsons (ssimss) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Glosārijs";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Parāda terminus un to definīcijas.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Glosārijs";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Glosārija izvēlne";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "pievieno glosārija izvēlni mājas lapai.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Glosārija saraksts";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "pievieno glosārija sarakstu mājas lapai.";
 
?>
