<?php
/**
 * TL_ROOT/system/modules/glossary/languages/lv/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Lettisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Ivo Simsons (ssimss) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Nosaukums";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Lūdzu ievadiet glosārija nosaukumu.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Pārskatīšanas datums";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Pēdējās pārskatīšanas datums un laiks";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Nosaukums";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Dzēšot glosāriju tiks izdzēsti arī visi tā termini. Vai tiešām vēlaties dzēst glosāriju ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Jauns glosārijs";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Izveidot jaunu glosāriju";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Glosārija detaļas";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Rādīt glosārija ID %s detaļas";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Rediģēt glosāriju";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Rediģēt glosāriju ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopēt glosāriju";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopēt glosāriju ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Dzēst glosāriju";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Dzēst glosāriju ID %s";
 
?>
