<?php
/**
 * TL_ROOT/system/modules/glossary/languages/no/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Norwegisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Thorbjørn Kahrs Fabricius (Thorbjørn), www.pixeldynamics.no 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Ordliste";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "List termer og definisjoner";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Ordliste";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Ordlistemeny";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Legg til en ordlistemeny til nettstedet";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Ordliste";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "Legg til en ordliste til nettstedet";
 
?>
