<?php
/**
 * TL_ROOT/system/modules/glossary/languages/no/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Norwegisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Thorbjørn Kahrs Fabricius (Thorbjørn), www.pixeldynamics.no 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Tittel";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Vennligst legg inn tittel for ordlisten";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Tittel";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Sletting av ordliste vil også slette alle elementer! Vil du virkelig slette ordlisten ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Ny ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Legg til ny ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Detaljer for ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Vis detaljer for ordliste ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Rediger ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Rediger ordliste ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopier ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopier ordliste ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Slett ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Slett ordliste ID %s";
 
?>
