<?php
/**
 * TL_ROOT/system/modules/glossary/languages/no/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Norwegisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Thorbjørn Kahrs Fabricius (Thorbjørn), www.pixeldynamics.no 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Term";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Vennligst legg inn en term";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Forfatter";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Her kan du endre forfatter av definisjonen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definisjon";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Vennligst legg inn en definisjon.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Legg til bilde";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Legg til et bilde til definisjonen";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Legg til en tilleggsfil";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Legg til en eller flere nedlastbare filer til definisjonen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Tilleggsfil";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Vennligst legg til ønskede filer";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Term og forfatter";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definisjon";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Artikkelbilde";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Tilleggsfil";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Ny term";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Legg til ny term";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detaljer for term";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Vis detaljer for term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Rediger term";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Rediger term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Flytt term";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Flytt term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopier term";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopier term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Slett term";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Slett term ID %s";
 
?>
