<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sr/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Serbisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Janos Guljas (Janos), http://www.janos.in.rs 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Речник";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Листа термина и њихових дефиниција.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Речник";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Мени речника";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "додавање менија речника на сајт";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Листа речника";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "додавање листе речника на сајт";
 
?>
