<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sr/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Serbisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Janos Guljas (Janos), http://www.janos.in.rs 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Унесите термин.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Аутор";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Овде можете променити аутора термина.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Дефиниција";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Унесите дефиницују термина.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Додај слику";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Додајте слику уз дефиницију.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Додај додатке";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Додајте један или више фајлова уз дефиницију.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Додаци";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Изаберите фајлове које желите да додате.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Термин и аутор";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Дефиниција";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Слика";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Додаци";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Нов термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Направи нови термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Детаљи термина";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Приказ детаља термина ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Уреди термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Уреди термин ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Копирај термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Копирај термин ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Избриши термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Избриши термин ID %s";
 
?>
