<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sr/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Serbisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Janos Guljas (Janos), http://www.janos.in.rs 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Наслов";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Унесите налов речника.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Датум ревизије";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Датум и време последње ревизије.";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Наслов";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Брисањем речника такође бришете и све речи из њега! Да ли стварно желите да избришете речник ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Нови речник";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Направи нови речник";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Детаљи речника";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Прикажи детеље речника ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Уреди речник";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Уреди речник ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Копирај речник";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Копирај речник ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Избриши речник";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Избриши речник ID %s";
 
?>
