<?php
/**
 * TL_ROOT/system/modules/glossary/languages/sr/tl_module.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Serbisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Janos Guljas (Janos), http://www.janos.in.rs 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Речници";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Изаберите један или више речника.";
 
?>
