<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pt/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Portugiesisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Serena Kierzkowski (serenatk) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Glossário";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Listar termos e suas definições.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Glossário";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Menu do Glossário";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Adiciona um menu do glossário ao site.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Lista do Glossário";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "adiciona uma lista do glossário ao site.";
 
?>
