<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pt/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Portugiesisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Serena Kierzkowski (serenatk) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Título";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Por favor, insira o título do glossário";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Data de revisão";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Data e hora da última revisão";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Título";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Se um glossário for deletado todos os seus termos também serão! Você quer realmente apagar o glossário com ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Novo glossário";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Criar um novo glossário";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Detalhes do glossário";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Mostra detalhes do glossário com ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Editar glossário";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Editar glossário com ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Copiar glossário";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Copiar glossário com ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Deletar glossário";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Deletar glossário com ID %s";
 
?>
