<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pt/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Portugiesisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Serena Kierzkowski (serenatk) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Favor inserir o termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Aqui você pode modificar o autor da definição.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definição";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Favor inserir a definição.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Adicionar uma imagem";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Adicionar uma imagem à definição.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Adicionar anexos";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Adicione à definição um ou mais arquivos para serem baixados.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Anexos";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Por favor, escolha os arquivos a serem anexados.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Termo e autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definição";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Imagem do artigo";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Anexos";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Novo termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Criar novo termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detalhes do termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Mostrar detalhes do termo com ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Editar termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Editar termo com ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Mover Termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Mover termo com ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Copiar termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Copiar termo com ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Deletar termo";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Deletar termo com ID %s";
 
?>
