<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ru/modules.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Russian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Глоссарий";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Список терминов и их определений.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Глоссарий";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Меню глоссария";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "добавляет меню глоссария на веб-сайт.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Список глоссария";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "добавляет список глоссария на веб-сайт.";
 
?>
