<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ru/tl_glossary_term.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Russian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Пожалуйста, введите термин.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Автор";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Здесь вы можете изменить автора этого определения.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Определение";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Пожалуйста, введите определение.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Добавить изображение";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Добавить изображение к определению.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Добавить вложение";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Добавьте один или несколько загружаемых файлов к определению.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Вложения";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Пожалуйста, выберите файлы, которые вы хотите вложить.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Термин и автор";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Определение";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Изображение статьи";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Вложения";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Новый термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Создать новый термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Детали термина";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Показать детали термина ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Редактировать термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Редактировать термин ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Переместить термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Переместить термин ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Дублировать термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Дублировать термин ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Удалить термин";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Удалить термин ID %s";
 
?>
