<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ru/tl_glossary.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Russian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Пожалуйста, введите название глоссария.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Дата изменения";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Дата и время последнего изменения";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Название";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Удаление глоссария, также удалит все термины! Вы действительно хотите удалить глоссарий ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Новый глоссарий";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Создать новый глоссарий";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Детали глоссария";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Показать детали глоссария ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Редактировать глоссарий";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Редактировать глоссарий ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Дублировать глоссарий";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Дублировать глоссарий ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Удалить глоссарий";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Удалить глоссарий ID %s";
 
?>
