<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ru/tl_module.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Russian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Глоссарий";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Пожалуйста, выберите один или несколько глоссариев.";
 
?>
