<?php
/**
 * TL_ROOT/system/modules/glossary/languages/cs/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.3 stable 
 * Czech translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Lukas Zlesak (lzlesak), lzlesak 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Slovník";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Seznam výrazů a jejich výkladů";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Slovník";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Nabídka slovníku";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "vloží nabídku slovníku na web.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Seznam slovníku";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "vloží seznbam slovníku na web.";
 
?>
