<?php
/**
 * TL_ROOT/system/modules/glossary/languages/cs/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.3 stable 
 * Czech translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Lukas Zlesak (lzlesak), lzlesak 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Název";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Zadejte prosím název slovníku";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Datum revize";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Datum a čas poslední revize";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Název";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Smazáním slovníku budou smazány také všechny jeho výrazy! Opravdu chcete smazat slovník ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nový slovník";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Vytvoří nový slovník";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Detaily slovníku";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Zobrazí detaily slovníku ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Upravit slovník";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Upraví slovník ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopírovat slovník";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Zkopíruje slovník ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Smazat slovník";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Smaže slovník ID %s";
 
?>
