<?php
/**
 * TL_ROOT/system/modules/glossary/languages/cs/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.3 stable 
 * Czech translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Lukas Zlesak (lzlesak), lzlesak 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Zadejte prosím výraz.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Zde můžete změnit autora výkladu.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Výklad.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Zadejte prosím výklad.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Přidat obrázek";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Vloží obrázek k výkladu.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Přidat přílohy";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Vloží jeden nebo více příloh (stáhnutelné soubory) k výkladu.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Přílohy";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Vyberte prosím soubory, které chcete přiložit.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Výraz a autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Váklad";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Obrázek článku";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Přílohy";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nový výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Vytvoří nový výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detaily výrazu";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Zobrazí detail výrazu ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Upravit výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Upraví váraz ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Přesunout výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Přesune výraz ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopírovat výraz";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Zkopíruje výraz ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Smazání výrazu";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Smaže výraz ID %s";
 
?>
