<?php
/**
 * TL_ROOT/system/modules/glossary/languages/da/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Dänisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Jesper R. Meyer (jrm) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Skriv betegnelsen";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Forfatter";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Her kan du ændre forfatteren til betegnelsen";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Defination";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Skriv definationen";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Tilføj et billede";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Tilføj et billede til definationen";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Tilføj bilag";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Tilføj en eller flere bilag til definationen";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Bilag";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Vælg venligst filen du vil vedhæfte";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Betegnelse og forfatter";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Defination";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Artikel billede";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Bilag";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Ny betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Opret en ny betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detaljer for betegnelsen";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Vis detaljer for betegnelse ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Rediger betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Rediger betegnelse ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Flyt betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Flyt betegnelse ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopier betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopier betegnelse ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Slet betegnelse";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Slet betegnelse ID %s";
 
?>
