<?php
/**
 * TL_ROOT/system/modules/glossary/languages/da/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Dänisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Jesper R. Meyer (jrm) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Skriv ordlistens titel";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Revisionsdato";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Date og tid for seneste revision";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Hvis du sletter en ordliste, slettes alle betegnelser også! Er du sikker på du vil slette ordliste ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Ny ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Opret en ny ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Rediger ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Rediger ordliste ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopier ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopier ordliste ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Slet ordliste";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Slet ordliste OID %s";
 
?>
