<?php
/**
 * TL_ROOT/system/modules/glossary/languages/uk/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Ukrainisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Mayovets Vasyl (mayvas), http://www.msm-tech.net 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Словник";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Список термінів та їх визначень";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Словник";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Меню словника";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "додати меню словника до сайту";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Список словників";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "додати список словників до сайту";
 
?>
