<?php
/**
 * TL_ROOT/system/modules/glossary/languages/uk/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Ukrainisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Mayovets Vasyl (mayvas), http://www.msm-tech.net 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Введіть, будь ласка, термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Автор";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Тут Ви можете змінити автора визначення";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Визначення";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Введіть, будь ласка, визначення для даного терміна";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Додати малюнок";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Додати визначення до малюнку";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Додати вкладення";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Дадайте один, або більше прикріплених файлів";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Додатки";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Виберіть, будь ласка, файли які Ви хочете прикріпити";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Терміни та автор";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Визначення";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Малюнок статті";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Додатки";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Новий термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Створити новий термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Детальна інформація про термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Показати детальну інформацію про обраний термін ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Редагувати термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Редагувати термін ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Перемістити термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Перемістити термін ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Копіювати термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Копіювати термін ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Видалити термін";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Видалити термін ID %s";
 
?>
