<?php
/**
 * TL_ROOT/system/modules/glossary/languages/uk/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Ukrainisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Mayovets Vasyl (mayvas), http://www.msm-tech.net 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Заголовок";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Введіть, будь ласка, заголовок словника";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Дата змін";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Дата та час останніх змін";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Заголовок";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "При видаленні словника, буде також видалені всі внесені в нього дані! Ви дійсно хочете видалити глосарій ID% S?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Новий словник";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Створити новий словник";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Детальна інформація про словник";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Переглянути детальну інформацію про словник";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Редагувати словник";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Редагувати словник ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Копіювати словник";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Копіювати словник ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Видалити словник";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Видалити словник ID %s";
 
?>
