<?php
/**
 * TL_ROOT/system/modules/glossary/languages/uk/tl_module.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Ukrainisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Mayovets Vasyl (mayvas), http://www.msm-tech.net 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Словники";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Будь ласка, виберіть один або більше словників";
 
?>
