<?php
/**
 * TL_ROOT/system/modules/glossary/languages/nl/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Verklarende woordenlijst";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Termen en hun definities.";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Verklarende woordenlijst";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Woordenlijst menu";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "voegt een woordenlijst menu toe aan de website.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Woordenlijst";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "voegt een woordenlijst toe aan de website.";
 
?>
