<?php
/**
 * TL_ROOT/system/modules/glossary/languages/nl/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Voer een titel voor de woordenlijst in.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Datum herziening";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Datum en tijd van de laatste herziening";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Verwijderen van een woordenlijst verwijderd ook al haar termen.Wilt u werkelijk woordenlijst ID %s verwijderen?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nieuwe woordenlijst";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Nieuwe woordenlijst aanmaken";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Woordenlijst details";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Toon de details van woordenlijst ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Bewerk woordenlijst";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Bewerk woordenlijst ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopieer woordenlijst";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopieer woordenlijst ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Verwijder woordenlijst";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Verwijder woordenlijst ID %s";
 
?>
