<?php
/**
 * TL_ROOT/system/modules/glossary/languages/nl/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Term";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Voer een nieuwe term in.";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Auteur";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Hier kunt u de auteur van de definitie wijzigen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definitie";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Geef een definitie in.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Voeg een afbeelding toe";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Voeg een afbeelding toe aan de definitie.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Voeg bijlage toe";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Voeg een of meerdere downloadbare bestanden toe aan een definitie.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Bijlagen";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Kies de bestanden welke u wilt toevoegen.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Term en auteur";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definitie";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Artikel afbeelding";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Bijlagen";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nieuwe term";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Maak een nieuwe term aan";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Details van een term";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Toon details van term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Bewerk term";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Bewerk term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Verplaats term";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Verplaats term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopieer term";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopieer term ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Verwijder term";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Verwijder term ID %s";
 
?>
