<?php
/**
 * TL_ROOT/system/modules/glossary/languages/it/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Glossario";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Elenca i termini e le loro definizioni";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Glossario";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Menu glossario";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "aggiunge un menu glossario al sito";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Elenco glossario";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "aggiunge un elenco dei termini del glossario al sito";
 
?>
