<?php
/**
 * TL_ROOT/system/modules/glossary/languages/it/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Inserisci il titolo da assegnare al glossario";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Data revisione";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Data e ora dell'ultima revisione";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titolo";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Eliminando un glossario verranno rimossi tutti i termini contenuti in esso! Vuoi veramente eliminare il glossario ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nuovo glossario";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Crea un nuovo glossario";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Dettagli glossario";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Mostra i dettagli del glossario ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Modifica glossario";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Modifica glossario ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Copia glossario";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Copia glossario ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Elimina glossario";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Elimina glossario ID %s";
 
?>
