<?php
/**
 * TL_ROOT/system/modules/glossary/languages/it/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Inserisci il termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autore";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Modifica l'autore della definizione";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definizione";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Inserisci la definizione del termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Aggiungi un immagine";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Aggiungi un immagine alla definizione";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Aggiungi allegati";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Allega uno o più file alla definizione";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Allegati";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Seleziona i file da allegare";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Termine e autore";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definizione";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Immagine articolo";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Allegati";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nuovo termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Crea un nuovo termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Dettagli termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Mostra i dettagli del termine ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Modifica termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Modifica termine ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Sposta termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Sposta termine ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Copia termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Copia termine ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Elimina termine";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Elimina termine ID %s";
 
?>
