<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ro/modules.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Ionuţ PURCARU (purcaruionut), www.iroot.ro 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Glosar";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Listează termeni şi definiţii";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Glosar";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Meniu glosar";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "Adaugă un meniu de tip glosar la website.";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Listă de glosare";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "Adaugă o listă de glosare la website";
 
?>
