<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ro/tl_glossary.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Ionuţ PURCARU (purcaruionut), www.iroot.ro 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Titlu";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Introduceţi titlul glosarului";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Data reviziei";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Data şi ora ultimei revizii";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Titlu";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Ştergerea unui glosar va şterge şi toţi termenii acestuia! Doriţi ştergerea glosarului ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nou glosar";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Adaugă un nou glosar";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Detalii glosar";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Arată detaliile glosarului ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Editează glosar";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Editează glossarul ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Copiază glosar";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Copiază glosarul ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Şterge glosar";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Şterge glosarul ID %s";
 
?>
