<?php
/**
 * TL_ROOT/system/modules/glossary/languages/ro/tl_glossary_term.php 
 * 
 * Contao extension: glossary 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2011 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Ionuţ PURCARU (purcaruionut), www.iroot.ro 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Introduceţi termenul";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Aici puteţi schimba autorul definiţiei.";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Definiţie";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Introduceţi definiţia";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Adaugă imagine";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Adaugă o imagine la definiţie.";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Include fişiere";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Adaugă unul sau mai multe fişiere la definiţie care se pot descărca.";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Fişiere ataşate";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Alegeţi fişierele pe care le doriţi ataşate";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Termenşi autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definiţie";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Imagine articol";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Fişiere ataşate";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nou termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Adaugă un nou termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Detalii termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Arată detaliile termenului ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Editează termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Editează termenul ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Mută termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Mută termenul ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Copiază termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Copiază termenul ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Şterge termen";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Şterge termenul ID %s";
 
?>
