<?php
/**
 * TL_ROOT/system/modules/glossary/languages/bg/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Bulgarisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Krassimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Речник";
 
?>
