<?php
/**
 * TL_ROOT/system/modules/glossary/languages/bg/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Bulgarisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Krassimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Заглавие";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Моля, въведете заглавие на речника.";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Дата на версията";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Дата и време на последната версия.";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Заглавие";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Изтриването на речник води до изтриване на записите в него! Наистина ли искате да изтриете речник с ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Нов речник";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Създаване на нов речник";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Подробности за речник";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Изглед на подробностите за речник с ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Редакция на речник";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Редакция на речник с ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Копиране на речник";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Копиране на речник с ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Изтриване на речник";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Изтриване на речник с ID %s";
 
?>
