<?php
/**
 * TL_ROOT/system/modules/glossary/languages/bg/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Bulgarisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Krassimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Понятие";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Моля, въведете понятие.";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Определение и автор";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Определение";
 
?>
