<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pl/modules.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Polnisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['glossary']['0'] = "Słownik";
$GLOBALS['TL_LANG']['MOD']['glossary']['1'] = "Lista terminów i ich opis";
$GLOBALS['TL_LANG']['FMD']['glossary'] = "Słownik";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['0'] = "Menu słownika";
$GLOBALS['TL_LANG']['FMD']['glossaryMenu']['1'] = "dodaj menu słownika do strony";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['0'] = "Lista słownika";
$GLOBALS['TL_LANG']['FMD']['glossaryList']['1'] = "dodaj listę słownika do strony";
 
?>
