<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pl/tl_glossary.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Polnisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary']['title']['0'] = "Tytuł";
$GLOBALS['TL_LANG']['tl_glossary']['title']['1'] = "Podaj tytuł słownika";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['0'] = "Data zmiany";
$GLOBALS['TL_LANG']['tl_glossary']['tstamp']['1'] = "Data i czas ostatniej zmiany";
$GLOBALS['TL_LANG']['tl_glossary']['title_legend'] = "Tytuł";
$GLOBALS['TL_LANG']['tl_glossary']['deleteConfirm'] = "Usunięcie słownika spowoduje usunięcie wszystkich jego terminów! Czy na pewno chcesz usunąć słownik ID %s?";
$GLOBALS['TL_LANG']['tl_glossary']['new']['0'] = "Nowy słownik";
$GLOBALS['TL_LANG']['tl_glossary']['new']['1'] = "Utwórz nowy słownik";
$GLOBALS['TL_LANG']['tl_glossary']['show']['0'] = "Szczegóły słownika";
$GLOBALS['TL_LANG']['tl_glossary']['show']['1'] = "Pokaż szczegóły słownika ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['0'] = "Edytuj słownik";
$GLOBALS['TL_LANG']['tl_glossary']['edit']['1'] = "Edytuj słownik ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['0'] = "Kopiuj słownik";
$GLOBALS['TL_LANG']['tl_glossary']['copy']['1'] = "Kopiuj słownik ID %s";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['0'] = "Usuń słownik";
$GLOBALS['TL_LANG']['tl_glossary']['delete']['1'] = "Usuń słownik ID %s";
 
?>
