<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pl/tl_glossary_term.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Polnisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['0'] = "Termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['term']['1'] = "Wprowadź termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['author']['1'] = "Tu możesz wprowadzić autora opisu";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['0'] = "Opis";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition']['1'] = "Wprowadź opis";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['0'] = "Dodaj obrazek";
$GLOBALS['TL_LANG']['tl_glossary_term']['addImage']['1'] = "Dodaj obrazek do opisu";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['0'] = "Dodaj załącznik";
$GLOBALS['TL_LANG']['tl_glossary_term']['addEnclosure']['1'] = "Dodaj jeden lub więcej plików do pobrania";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['0'] = "Załączniki";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure']['1'] = "Zaznacz pliki, które chcesz załączyć";
$GLOBALS['TL_LANG']['tl_glossary_term']['title_legend'] = "Termin i autor";
$GLOBALS['TL_LANG']['tl_glossary_term']['definition_legend'] = "Definicja";
$GLOBALS['TL_LANG']['tl_glossary_term']['image_legend'] = "Obrazek";
$GLOBALS['TL_LANG']['tl_glossary_term']['enclosure_legend'] = "Załączniki";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['0'] = "Nowy termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['new']['1'] = "Utwórz nowy termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['0'] = "Szczegóły terminu";
$GLOBALS['TL_LANG']['tl_glossary_term']['show']['1'] = "Pokaż szczegóły terminu ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['0'] = "Edytuj termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['edit']['1'] = "Edytuj termin ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['0'] = "Przenieś termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['cut']['1'] = "Przenieś termin ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['0'] = "Kopiuj termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['copy']['1'] = "Kopiuj termin ID %s";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['0'] = "Usuń termin";
$GLOBALS['TL_LANG']['tl_glossary_term']['delete']['1'] = "Usuń termin ID %s";
 
?>
