<?php
/**
 * TL_ROOT/system/modules/glossary/languages/pl/tl_module.php 
 * 
 * TYPOlight extension: glossary 1.0.0 stable 
 * Polnisch translation file 
 * 
 * Copyright : ©Leo Feyer 2005-2010 
 * License   : LGPL 
 * Author    : Leo Feyer (leo), http://www.inetrobots.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['glossaries']['0'] = "Słowniki";
$GLOBALS['TL_LANG']['tl_module']['glossaries']['1'] = "Zaznacz jeden lub więcej słowników";
 
?>
